### ISSUE TITLE
1.21.4 and future updates

### ISSUE THREAD

**Issue by Xotsu** [TreeOfSelf/CarpetSkyAdditions-Reborn#10]
Hey, just wanted to get a clarification if this repo is a permanent continuation of jsorrell's work and your plans going forward like keeping up with the latest drops (1.21.4) onwards. It has been a while since the official mod was updated so maybe you have more details?
P.s. Is there an option to disable trial spawner spawning? I saw a suggestion of drowning a blaze into a breeze and was wandering if you had any plans on implementing alternatives like this?

Thank you

**Comment by Seigmannen** [comment]
I cannot answer for the update to 1.21.4. For the trial spawner there is a setting for disabling it use "/carpetskyadditions list" and you should be able to find it.

**Comment by TreeOfSelf** [comment]
Basically, I ran an anarchy server that uses the mod, wanted to keep my server updated, so I started updating the mod. Releasing my updates so that other people who want to play on later versions can play also. If jsorrell continues development on latest versions of his mod, than there would be no need for this mod. It is only here to cover in jsorrell's absence. 

Yeah I would like to do something better with the Trial Chambers in the future, they are kind of half-baked.
