### ISSUE TITLE
Better Trial Chamber Implementation Ideas

### ISSUE THREAD

**Issue by TreeOfSelf** [TreeOfSelf/CarpetSkyAdditions-Reborn#14]
I am interested in improving the way Trial Chambers are currently implemented, share your ideas here! Thanks.

**Comment by DrKhaoticSarcasm** [comment]
Maybe have the trial spawners spawn as normal spawners, and have they player manually place their indicated patterns in and have anvil drop on the mob to "push them in" to convert to their respective trial spawners?

**Comment by Xotsu** [comment]
As I understand the biggest issue with the spawners is their frequency and lack of difficulty in a skyblock word. I think a nice way to tackle both of these problems would be conditionally generating the entire trial chambers structure (shown below) if a user has something like bad omen from the Ominous Bottle effect and is within the trial chambers structure. Likewise after clearing, the chamber would despawn after a couple of minutes of set time (so he user can get out and doesn't fall into the void and no eyesore permanent blocks remain). A condition that the chambers can't start spawning if more than one existing block is inside the bounds would be required, to prevent accidental bad omen effects spawning chambers in the players existing builds, destroying them. Although with this approach the same structure could be reused, given the incompatibility of skyblock with exploration and the tools like MiniHUD or chunkbase required to even find the now hidden structures I think it's a reasonable vanilla-like alternative.
![Chambers Layout](https://minecraft.wiki/images/thumb/Trial_Chambers_layout.png/400px-Trial_Chambers_layout.png)

**Comment by Xotsu** [comment]
I'm also in favour of the above entity based spawnerless approach, it would be straight forward to automate and I'm assuming easier to implement as well.

**Comment by Seigmannen** [comment]
What if we bring a mob to the trial chamber, and this will start a trial chamber event (like the spawners do), and then the last one killed, has a chance to drop the key, If having the ominous effect, then it would be a ominous trial event, with a change to drop the ominous key. Could this make it more interesting?
When the event is complete, a vault might spawn, so it can be opened with a key.

**Comment by TreeOfSelf** [comment]
![2024-12-15_20 26 01](https://github.com/user-attachments/assets/cfa2ff7a-6a6a-4d5d-954e-68e213c7044f)
For now I just made it so Trial Chambers are just a breeze spawner, and a normal vault and ominous. But I am still open to improving it.

**Comment by rylry** [comment]
I like the direction this is going, but I still have three problems with the current implementation. First, it is extremely unbalanced. Players can get endgame items like golden apples and diamonds from vaults almost at day 1. My suggestion to fix this would be to have the player use something like blaze powder on the spawner to set the entity to Breeze and ignite the spawner. It would fit with the theme of the spawner and be balanced.

Second, the spawners do not reset after 30 minutes like they do in vanilla. This is happening because the EntityType is set using SpawnerBlockEntity instead of Spawner, and it can be fixed by modifying only a few lines of code in SkyBlockStructures. I checked the nbt data of skyblock generated spawner block entities after I applied the fix, and it was identical to a vanilla generated one. This problem would be automatically fixed by implementing spawner ignition in a way similar to SpawnEggItem.

Finally, I think that spawner and vault postitions should be slightly randomized instead of being in a line. It fits better with the theme of the mod and allows spawners to be farmed more easily without breaking vaults.

**Comment by TreeOfSelf** [comment]
I like the idea of having to set the spawners to activate, and good to know about the issue with the spawners not resetting. 

technically with the change of their only being 1 spawner, and their only being 1 of each vault type it would take a ton of bridging and luck to get specific items. 
In general, the trial chambers don't really fit Minecraft anyways and at least from I've heard in, they just aren't a feature players generally like, so it's hard to fit an already poor feature into skyblock in an interesting way. 


I can randomize the position of the spawner and the vaults, maybe have 1 spawner, and 2 vaults, the spawner isn't activated. if you bring a blaze to the overworld, it turns into a breeze, once it's a breeze and you get breeze rod, you can use that to turn the spawner into a breeze spawner. Maybe also have ways to turn the spawner into other mobs. 
I think that would be reasonable.

**Comment by Xotsu** [comment]
I seem to have a bug where the **ominous vaults** seem to take regular **trial keys** instead of expected **ominous trial keys**.

As for the implementation I disagree with:
> First, it is extremely unbalanced. Players can get endgame items like golden apples and diamonds from vaults almost at day 1.

Trial chambers provide an alternative to villager conversion and emerald farming instead of foxes (for getting apple saplings from wandering trader) in the early game, breaking the forced and very linear progression currently in the game. Likewise the loot is randomized and single use meaning that you'd likely need to visit several chambers in order to get the 8.3% golden apple drop and even the key/ emeralds aren't guaranteed. As for diamonds or other random loot, that can likewise be acquired **renewably** in normal survival's "day 1" with villagers so it doesn't feel game breaking imo. I will admit that the difficulty is laughable with the spawner dropping breezes into the void most of the time, which I think if fixed could make this quite a nice alternative game play experience.

**Comment by TreeOfSelf** [comment]
> Trial chambers provide an alternative to villager conversion and emerald farming instead of foxes (for getting apple saplings from wandering trader) in the early game, breaking the forced and very linear progression currently in the game. Likewise the loot is randomized and single use meaning that you'd likely need to visit several chambers in order to get the 8.3% golden apple drop and even the key/ emeralds aren't guaranteed.

That's a good point,  since the golden apple isn't guaranteed and is pretty low drop chance, you very well may spend more time/resources bridging around than just following the regular progression. It also is kind of interesting to have multiple ways of doing things.

**Comment by TreeOfSelf** [comment]
> Second, the spawners do not reset after 30 minutes like they do in vanilla. This is happening because the EntityType is set using SpawnerBlockEntity instead of Spawner, and it can be fixed by modifying only a few lines of code in SkyBlockStructures. I checked the nbt data of skyblock generated spawner block entities after I applied the fix, and it was identical to a vanilla generated one. This problem would be automatically fixed by implementing spawner ignition in a way similar to SpawnEggItem.



I'm looking into what you are saying about the spawners not resetting, I just tested using a tick warp and the spawner reset normally after 30 minutes for me. When you say SpawnerBlockEntity and Spawner, those aren't used for Trial Chambers.

**Comment by TreeOfSelf** [comment]
Upcoming version has Trial Spawner starting 8 blocks away from the 2 vaults.
The Trial Spawner now starts deactivated, you can bring a blaze to the overworld to convert it to a breeze (won't happen if its nametagged) 

A breeze rod can now be used to activate a trial spawner to become a breeze trial spawner.  


Feel free to open a new issue if this isn't satisfactory.
